version: '3.9'

services:
  frontend:
    build: ./frontend
    container_name: facerecog-front
    ports:
      - '3000:5173'
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: facerecog-back
    ports:
      - '8000:8000'
